### ISSUE TITLE
ヘッダータイトル aタグ修正

### ISSUE THREAD

**Issue by OR6107** [Kaito-sokuho/kaito-sokuho.github.io#36]
from #35 
触ると色変わっちゃおう
`::` で修正

**Comment by Nakano-oeno-oji** [comment]
まだ変更が反映されてないようじゃ

**Comment by OR6107** [comment]
これは
a タグにclassつけて
```css
a:link, a:visited {
    color: blue;
    font-weight: 600;
}
```
とすればいいはず
